// Public Cloudinary delivery URLs. Generated by scripts/migrate-cloudinary.mjs.
export const MEDIA = {
  "logo": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865130/cafe-barrio/logo-cafe-rio.jpg",
  "hero": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865413/cafe-barrio/hero-photo.jpg",
  "productFallback": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865109/cafe-barrio/coffee-cusco.webp",
  "heroFallback": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865117/cafe-barrio/hero.svg",
  "legacyUrls": {
    "/images/blend.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865099/cafe-barrio/blend.svg",
    "/images/ceramic-mug.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865107/cafe-barrio/ceramic-mug.webp",
    "/images/coffee-blend.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865107/cafe-barrio/coffee-blend.webp",
    "/images/coffee-cajamarca.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865108/cafe-barrio/coffee-cajamarca.webp",
    "/images/coffee-cusco.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865109/cafe-barrio/coffee-cusco.webp",
    "/images/coffee.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865110/cafe-barrio/coffee.svg",
    "/images/french-press.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865117/cafe-barrio/french-press.webp",
    "/images/hero.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865117/cafe-barrio/hero.svg",
    "/images/kit-compartir.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865125/cafe-barrio/kit-compartir.webp",
    "/images/kit-ritual.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865125/cafe-barrio/kit-ritual.webp",
    "/images/kit.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865126/cafe-barrio/kit.svg",
    "/images/logo-cafe-rio.jpg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865130/cafe-barrio/logo-cafe-rio.jpg",
    "/images/manual-grinder.webp": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865130/cafe-barrio/manual-grinder.webp",
    "/images/mug.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865131/cafe-barrio/mug.svg",
    "/images/press.svg": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865138/cafe-barrio/press.svg",
    "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85": "https://res.cloudinary.com/dgj2ol5r1/image/upload/v1790865413/cafe-barrio/hero-photo.jpg"
  }
} as const;
