CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL, description VARCHAR(1500) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price > 0),
    stock INTEGER NOT NULL CHECK (stock >= 0), image_url VARCHAR(1000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    category_id BIGINT NOT NULL REFERENCES categories(id)
);
CREATE INDEX idx_product_category ON products(category_id);
CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(120) NOT NULL, phone VARCHAR(20) NOT NULL,
    address VARCHAR(300) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDIENTE','EN_PREPARACION','ENTREGADO')),
    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    request_key VARCHAR(36) NOT NULL UNIQUE, request_hash VARCHAR(64) NOT NULL
);
CREATE INDEX idx_order_status_date ON purchase_orders(status, created_at);
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES purchase_orders(id),
    product_id BIGINT NOT NULL REFERENCES products(id), product_name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price > 0),
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal > 0)
);
CREATE INDEX idx_item_order ON order_items(order_id);
